### ISSUE TITLE
[iter2] 2.4 Search table - Links

### ISSUE THREAD

**Issue by haudquaquam** [cs169/fa23-chips-10.5-22#20]
As a user viewing the top 20 candidate table on the search page for a specific cycle and category, I should (probably) be able to click a link for each candidate in the table to view more information.

**Comment by snowshoes7** [comment]
Won't do. Google civic api doesn't correspond 1:1 with the results from this list as many are no longer representatives so this would be unhelpful.

**Comment by snowshoes7** [comment]
Not planned
